#!/usr/bin/python
import sys
from topic_function import *
from zookeeper_function import *
from print_function import *
from connect_function import *
from console_function import *
from consumergroup_function import *
from server_function import *
from common import *

try:
    import requests
except ImportError:
    raise ImportError('Module Requests not found. Install it and try again !')

if (len(sys.argv) <= 1):
    usage()
elif not os.getenv('KAFKA_HOME') or not os.getenv('KAFKA_BROKERS') or not os.getenv('KAFKA_ZOOKEEPER') or not os.getenv('KAFKA_CONNECT'):
    print getMissingEnvVar()
else:
    if sys.argv[1] in ["zookeeper","server","topic","console","consumergroup","connect"]:
        locals()[sys.argv[1]](sys.argv)
    else:
        usage()
